# Generated by Django 2.2 on 2019-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_auto_20190410_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='star_rate',
            field=models.CharField(choices=[(5, '⭐️⭐️⭐️⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (3, '⭐️⭐️⭐️'), (2, '⭐️⭐️'), (1, '⭐️')], default=1, max_length=5),
        ),
    ]
