# Generated by Django 2.2 on 2019-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20190410_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
