# Generated by Django 2.2 on 2019-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_auto_20190410_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='star_rate',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=1),
        ),
    ]
