# Generated by Django 2.2 on 2019-04-28 15:10

from django.db import migrations, models
import rate.models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_auto_20190410_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=rate.models.get_image_path),
        ),
    ]
