# Generated by Django 2.2 on 2019-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
