# Generated by Django 2.2.1 on 2019-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20190507_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(default='#', null=True, upload_to=''),
        ),
    ]
