# Generated by Django 2.2.1 on 2019-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20190516_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
