# Generated by Django 2.2 on 2019-05-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_time',
        ),
    ]
