# Generated by Django 2.2 on 2019-05-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0014_remove_comment_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
    ]
