# Generated by Django 2.2 on 2019-05-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0015_auto_20190502_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
