# Generated by Django 2.2 on 2019-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0016_auto_20190502_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_user',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
