# Generated by Django 2.2 on 2019-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0017_comment_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
