# Generated by Django 2.2 on 2019-04-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0011_auto_20190429_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
